"""
create_attr_cm_model_features.py
-------------------------------
Create a patient-level model feature table using the patient journey outputs.

This is a first-pass modeling dataset built on top of the patient journey event
and milestone tables. It creates a label for ATTR-CM diagnosis and a compact set
of pre-index clinical features for downstream modeling.

Usage:
    py -3 create_attr_cm_model_features.py
"""

import os
import sys

from create_undiagnosed_output_table import build_session

EVENT_TABLE = "VAW_AMER_DESIGN.US_VYNDA_DT_2.US_VYNDA_DT_2_PATIENT_JOURNEY_EVENTS_INF"
MILESTONE_TABLE = "VAW_AMER_DESIGN.US_VYNDA_DT_2.US_VYNDA_DT_2_PATIENT_JOURNEY_MILESTONES_INF"
OUTPUT_TABLE = "VAW_AMER_DESIGN.US_VYNDA_DT_2.US_VYNDA_DT_2_ATTR_CM_MODEL_FEATURES_INF"


def build_feature_sql():
    return """
WITH patient_labels AS (
    SELECT
        PATIENT_ID,
        CASE WHEN FIRST_ATTR_CM_DX_DATE IS NOT NULL THEN 1 ELSE 0 END AS LABEL_ATTR_CM,
        COALESCE(FIRST_ATTR_CM_DX_DATE, LAST_CLAIM_DATE) AS INDEX_DATE,
        FIRST_CLAIM_DATE,
        LAST_CLAIM_DATE,
        FIRST_HF_DATE,
        FIRST_HFPEF_DATE,
        FIRST_AFIB_DATE,
        FIRST_RED_FLAG_DATE,
        TOTAL_CONDITIONS,
        FLAG_2PLUS_CONDITIONS,
        FLAG_2PLUS_AND_HF,
        FLAG_2PLUS_AND_HFPEF,
        RED_FLAGS_BEFORE_ATTR_DX,
        DAYS_FROM_FIRST_HF_TO_ATTR_DX,
        DAYS_FROM_FIRST_RED_FLAG_TO_ATTR_DX,
        DAYS_FROM_2PLUS_TO_ATTR_DX
    FROM VAW_AMER_DESIGN.US_VYNDA_DT_2.US_VYNDA_DT_2_PATIENT_JOURNEY_MILESTONES_INF
),
pre_index_events AS (
    SELECT
        e.PATIENT_ID,
        e.EVENT_NAME,
        e.EVENT_DATE,
        p.INDEX_DATE,
        p.LABEL_ATTR_CM
    FROM VAW_AMER_DESIGN.US_VYNDA_DT_2.US_VYNDA_DT_2_PATIENT_JOURNEY_EVENTS_INF e
    INNER JOIN patient_labels p
        ON p.PATIENT_ID = e.PATIENT_ID
    WHERE e.EVENT_DATE <= p.INDEX_DATE
),
feature_rollup AS (
    SELECT
        p.PATIENT_ID,
        p.LABEL_ATTR_CM,
        p.INDEX_DATE,
        p.FIRST_CLAIM_DATE,
        p.LAST_CLAIM_DATE,
        p.FIRST_HF_DATE,
        p.FIRST_HFPEF_DATE,
        p.FIRST_AFIB_DATE,
        p.FIRST_RED_FLAG_DATE,
        p.TOTAL_CONDITIONS,
        p.FLAG_2PLUS_CONDITIONS,
        p.FLAG_2PLUS_AND_HF,
        p.FLAG_2PLUS_AND_HFPEF,
        p.RED_FLAGS_BEFORE_ATTR_DX,
        p.DAYS_FROM_FIRST_HF_TO_ATTR_DX,
        p.DAYS_FROM_FIRST_RED_FLAG_TO_ATTR_DX,
        p.DAYS_FROM_2PLUS_TO_ATTR_DX,

        MAX(CASE WHEN e.EVENT_NAME = 'AFIB' THEN 1 ELSE 0 END) AS AFIB_PREINDEX_FLAG,
        COUNT(DISTINCT CASE WHEN e.EVENT_NAME = 'AFIB' THEN e.EVENT_DATE END) AS AFIB_PREINDEX_COUNT,

        MAX(CASE WHEN e.EVENT_NAME = 'HEART_FAILURE' THEN 1 ELSE 0 END) AS HF_PREINDEX_FLAG,
        COUNT(DISTINCT CASE WHEN e.EVENT_NAME = 'HEART_FAILURE' THEN e.EVENT_DATE END) AS HF_PREINDEX_COUNT,

        MAX(CASE WHEN e.EVENT_NAME = 'HFPEF' THEN 1 ELSE 0 END) AS HFPEF_PREINDEX_FLAG,
        COUNT(DISTINCT CASE WHEN e.EVENT_NAME = 'HFPEF' THEN e.EVENT_DATE END) AS HFPEF_PREINDEX_COUNT,

        MAX(CASE WHEN e.EVENT_NAME IN ('AFIB', 'CARPAL_TUNNEL_SYNDROME', 'AORTIC_STENOSIS', 'BICEP_TENDON_RUPTURE', 'SPINAL_STENOSIS', 'AV_BLOCK') THEN 1 ELSE 0 END) AS RED_FLAG_PREINDEX_FLAG,
        COUNT(DISTINCT CASE WHEN e.EVENT_NAME IN ('AFIB', 'CARPAL_TUNNEL_SYNDROME', 'AORTIC_STENOSIS', 'BICEP_TENDON_RUPTURE', 'SPINAL_STENOSIS', 'AV_BLOCK') THEN e.EVENT_DATE END) AS RED_FLAG_PREINDEX_COUNT,

        MAX(CASE WHEN e.EVENT_NAME IN ('PX_PYP', 'PX_IHC', 'PX_TAVR', 'PX_CARDIAC_MRI', 'PX_ECHO_CARDIOGRAPHY', 'PX_ECG', 'PX_GENETIC_TESTING', 'PX_PROTEIN_ELECTROPHORESIS', 'PX_FLC', 'PX_CARDIAC_BIOPSY') THEN 1 ELSE 0 END) AS ATTR_RELEVANT_PROCEDURE_PREINDEX_FLAG,
        COUNT(DISTINCT CASE WHEN e.EVENT_NAME IN ('PX_PYP', 'PX_IHC', 'PX_TAVR', 'PX_CARDIAC_MRI', 'PX_ECHO_CARDIOGRAPHY', 'PX_ECG', 'PX_GENETIC_TESTING', 'PX_PROTEIN_ELECTROPHORESIS', 'PX_FLC', 'PX_CARDIAC_BIOPSY') THEN e.EVENT_DATE END) AS ATTR_RELEVANT_PROCEDURE_PREINDEX_COUNT,

        MIN(CASE WHEN e.EVENT_NAME = 'AFIB' THEN DATEDIFF('day', e.EVENT_DATE, p.INDEX_DATE) END) AS DAYS_TO_FIRST_AFIB_FROM_INDEX,
        MIN(CASE WHEN e.EVENT_NAME = 'HEART_FAILURE' THEN DATEDIFF('day', e.EVENT_DATE, p.INDEX_DATE) END) AS DAYS_TO_FIRST_HF_FROM_INDEX,
        MIN(CASE WHEN e.EVENT_NAME = 'HFPEF' THEN DATEDIFF('day', e.EVENT_DATE, p.INDEX_DATE) END) AS DAYS_TO_FIRST_HFPEF_FROM_INDEX,
        MIN(CASE WHEN e.EVENT_NAME IN ('AFIB', 'CARPAL_TUNNEL_SYNDROME', 'AORTIC_STENOSIS', 'BICEP_TENDON_RUPTURE', 'SPINAL_STENOSIS', 'AV_BLOCK') THEN DATEDIFF('day', e.EVENT_DATE, p.INDEX_DATE) END) AS DAYS_TO_FIRST_RED_FLAG_FROM_INDEX
    FROM patient_labels p
    LEFT JOIN pre_index_events e
        ON e.PATIENT_ID = p.PATIENT_ID
    GROUP BY
        p.PATIENT_ID,
        p.LABEL_ATTR_CM,
        p.INDEX_DATE,
        p.FIRST_CLAIM_DATE,
        p.LAST_CLAIM_DATE,
        p.FIRST_HF_DATE,
        p.FIRST_HFPEF_DATE,
        p.FIRST_AFIB_DATE,
        p.FIRST_RED_FLAG_DATE,
        p.TOTAL_CONDITIONS,
        p.FLAG_2PLUS_CONDITIONS,
        p.FLAG_2PLUS_AND_HF,
        p.FLAG_2PLUS_AND_HFPEF,
        p.RED_FLAGS_BEFORE_ATTR_DX,
        p.DAYS_FROM_FIRST_HF_TO_ATTR_DX,
        p.DAYS_FROM_FIRST_RED_FLAG_TO_ATTR_DX,
        p.DAYS_FROM_2PLUS_TO_ATTR_DX
)
SELECT
    PATIENT_ID,
    LABEL_ATTR_CM,
    INDEX_DATE,
    FIRST_CLAIM_DATE,
    LAST_CLAIM_DATE,
    DATEDIFF('day', FIRST_CLAIM_DATE, INDEX_DATE) AS DAYS_FROM_FIRST_CLAIM_TO_INDEX,
    FIRST_HF_DATE,
    FIRST_HFPEF_DATE,
    FIRST_AFIB_DATE,
    FIRST_RED_FLAG_DATE,
    TOTAL_CONDITIONS,
    FLAG_2PLUS_CONDITIONS,
    FLAG_2PLUS_AND_HF,
    FLAG_2PLUS_AND_HFPEF,
    RED_FLAGS_BEFORE_ATTR_DX,
    DAYS_FROM_FIRST_HF_TO_ATTR_DX,
    DAYS_FROM_FIRST_RED_FLAG_TO_ATTR_DX,
    DAYS_FROM_2PLUS_TO_ATTR_DX,
    AFIB_PREINDEX_FLAG,
    AFIB_PREINDEX_COUNT,
    HF_PREINDEX_FLAG,
    HF_PREINDEX_COUNT,
    HFPEF_PREINDEX_FLAG,
    HFPEF_PREINDEX_COUNT,
    RED_FLAG_PREINDEX_FLAG,
    RED_FLAG_PREINDEX_COUNT,
    ATTR_RELEVANT_PROCEDURE_PREINDEX_FLAG,
    ATTR_RELEVANT_PROCEDURE_PREINDEX_COUNT,
    DAYS_TO_FIRST_AFIB_FROM_INDEX,
    DAYS_TO_FIRST_HF_FROM_INDEX,
    DAYS_TO_FIRST_HFPEF_FROM_INDEX,
    DAYS_TO_FIRST_RED_FLAG_FROM_INDEX
FROM feature_rollup
""".strip()


def main():
    output_table = os.getenv("SNOWFLAKE_OUTPUT_TABLE", OUTPUT_TABLE).strip()
    session = build_session()
    try:
        sql = f"CREATE OR REPLACE TABLE {output_table} AS\n{build_feature_sql()}"
        print(f"Creating model feature table: {output_table}")
        session.sql(sql).collect()
        count = session.table(output_table).count()
        print(f"Feature table row count: {count:,}")
        print("Done.")
    finally:
        session.close()


if __name__ == "__main__":
    sys.exit(main())

